version: 2
jobs:
  run:
    docker:
       - image: circleci/node:8.9
    steps:
       - checkout
       - run: echo "Installing"
       - run: cd client && npm install 
  build:
    docker:
      - image: 
    steps:
      - checkout
      - run: echo "Building"
      - run: npm run build
workflows:
  version: 2
  CircleciTesting:
    jobs:
      - run
      - build