version: 2
jobs:
  build1:
    docker:
     - image: circleci/node:9.6.1
    steps:
       - checkout
       - run: echo "Hello there!"
  build2:
    docker:
     - image: circleci/node:9.6.1
    steps:
      - checkout
      - run: echo "Good Bye"
  workflows:
    # Name the workflow "Welcome"
    CircleciTesting:
      # Run the welcome/run job in its own container
      jobs:
        - welcome/run
        - build1
        - build2