version: 2
jobs:
  Installing:
    docker:
       - image: circleci/node:8.9
    steps:
       - checkout
       - run: echo "Installing"
       - run: npm install 
  build:
    docker:
      - image: circleci/node:8.9
    steps:
      - checkout
      - run: echo "Building"
      - run: CI=true npm run build --prefix client
workflows:
  version: 2
  CircleciTesting:
    jobs:
      - Installing
      - build