version: 2.1
orbs:
  # Declare a dependency on the welcome-orb
  welcome: circleci/welcome-orb@0.3.1
  # JOBS String here
  jobs:
    build1:
      docker:
      - image: "circleci/node:9.6.1"
      steps:
        - checkout
        - run: echo "Hello there!"

    build2:
      docker:
      - image: "circleci/node:9.6.1"
      steps:
        - checkout
        - run: echo "Good Bye"

  workflows:
    # Name the workflow "Welcome"
    CircleciTesting:
      # Run the welcome/run job in its own container
      jobs:
        - welcome/run
        - build1
        - build2